### ISSUE TITLE
Complex Testing

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#1660]
Meta issue to track progress:

 - [x] Example tickbox
   - Example Note
   - [ ] Example subtickbox

**Regression**
- [x] test_coarse_nullspace
- [x] test_expressions
- @sv2518 done
- [x] test_facet_orientation
- @sv2518 done
- [x] test_snespatch
- @sv2518 working
- [x] test_interpolate
   - @nbouziani  done
- [x] test_l2_pullbacks
- [x] test_manifolds
- [x] test_mesh_generation
- [x] test_nested_FS_solves
  - @nbouziani working
- [x] test_periodic_2D 
- [x] test_periodic_interval_advection
  - @nbouziani done
- [x] test_nonlinear_stokes_hdiv
  - @nbouziani done
- [x] test_par_loops
- [x] test_patch_precompute_element_tensors
- [x] test_periodic_rectangle_advection 
- [x] test_pointeval_api
- [x] test_point_eval_cells
- [x] test_real_space
  @nbouziani 
- [x] test_stokes_hdiv_parallel
- [x] test_split
  - @nbouziani done
- [x] test_vertex_based_limiter

**Comment by ksagiyam** [comment]
**equation_bcs**
- [ ] test_bcs_reconstruct.py
- [ ] test_equation_bcs
@ksagiyam working

**Comment by nbouziani** [comment]
- [ ] test_nonlinear_stokes_hdiv
  - @nbouziani working
      When the residual form contains `inner(sym(grad(u)), grad(v)) *dx`, things work but for `inner(g(u) * sym(grad(u)), grad(v)) *dx` it yields an Arity error, what is the right math for that?
- [ ] test_split
  - @nbouziani working
      2 fails:
         - 1st is fixed
         - In /ufl/ufl/algorithms/check_arities.py l.173, the code seems to assume that conjugation is spurious if there are more than 2 Arguments, this reasoning does not seem to take into account that Argument can also be obtained when taking the Gateaux-derivative and not only via TestFunction

**Comment by dham** [comment]
@nbouziani I'll take a look at that derivative error case.

**Comment by sv2518** [comment]
Outsourcing slate comments from regression. 

**Slate** @sv2518 
- [ ] test_assemble_tensors.py: 6 failed, 74 passed, 14022 warnings 
  - Problems will resolve themselves as soon as I wrote a mapper from the complex C to complex C++ functions
- [x ] test_linear_algebra.py: all pass

**Comment by APaganini** [comment]
- [ ] test_l2pullback.py @APaganini  working on it

**Comment by wence-** [comment]
@APaganini this is due to extruded meshes getting nonsense coordinate fields. I will push a fix.

**Comment by nbouziani** [comment]
Failing tests in `firedrake_adjoint` (tests/pyadjoint tests are all passing):

- [ ] test_assemble.py                                                                                                                                    
- [ ] test_assignment.py                                                                                                                                   
- [ ] test_burgers_newton.py                                                                                                                                   
- [ ] test_dynamic_meshes.py                                                                                                                          
- [ ] test_hessian.py
- [ ] test_reduced_functional.py                                                                                                                          
- [ ] test_shape_derivatives.py 
- [ ] test_solving.py 
- [ ] test_split.py
- [ ] test_tlm.py

**Comment by wence-** [comment]
`tests/multigrid` Now all working.

**Comment by wence-** [comment]
OK, I ran the regression part of the test suite yesterday and had the following fails:

- [ ] tests/regression/test_locate_cell.py::test_locate_cell[False-point3-4] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[False-point4-5] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[False-point5-6] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[False-point6-7] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[False-point7-8] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[False-point8-9] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell_not_found[False] - AssertionError: assert 0 is None
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[True-point3-4] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[True-point4-5] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[True-point5-6] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[True-point6-7] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[True-point7-8] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell[True-point8-9] - assert False
- [ ] tests/regression/test_locate_cell.py::test_locate_cell_not_found[True] - AssertionError: assert 0 is None
- [ ] tests/regression/test_nonlinear_stokes_hdiv.py::test_nonlinear_stokes_hdiv - ufl.algorithms.check_arities.ArityMismatch: Adding expressions with non-matching form arguments ('v_0',) vs ('conj(v_...
- [ ] tests/regression/test_vertex_based_limiter.py::test_constant_field[periodic-interval] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_constant_field[periodic-square-tri] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_constant_field[periodic-square-quad] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_step_function_bounds[periodic-interval] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_step_function_bounds[periodic-square-tri] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_step_function_bounds[periodic-square-quad] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_step_function_loop[periodic-interval] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_step_function_loop[periodic-square-tri] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_step_function_loop[periodic-square-quad] - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
- [ ] tests/regression/test_vertex_based_limiter.py::test_parallel_limiting - loopy.diagnostic.LoopyTypeError: fmax does not support complex numbers
