### ISSUE TITLE
[meta] VertexOnlyMesh parallel creation improvements

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#2223]
There are, at present, some issues which affect the creation of VertexOnlyMesh when created in parallel.

As identified in #2178, it was implicitly assumed by me that VertexOnlyMesh would be created in one of two ways:
 1. All ranks providing the same list of vertex coordinates.
 2. Each rank providing a rank-specific list of coordinates where each coordinate is know _a priori_ to be in the rank domain (excluding the local halos which are always emptied of points.

This ignores a third case:

  3. With each rank providing a list of candidate points which may or may-not be in the rank-local domain and **also may or may-not be in the global domain**.

This was a clear design mistake which should be corrected for as follows:

- [x] Take case (1.) to be the default case and force coordinate points to be broadcast from rank 0. 
  - This can be easily done with the current implementation by setting `redundant == PETSC_TRUE` in [DMSwarmSetPointCoordinates](https://petsc.org/release/docs/manualpages/DMSWARM/DMSwarmSetPointCoordinates.html). A new kwarg should be added to the VertexOnlyMesh constructor allowing this to be over-ridden.
- [x] Support case (3.) by migrating points the their correct MPI rank. This is discussed in detail in #2178. Rough plan:
  1. [x] Broadcast all points to all ranks and use the existing implementation **(brute force but easy)**
  2. [x] Avoid so much communication by migrating only necessary points **(efficient but harder)**. Ways to do this:
     1. Update DMSWARM to allow this (ask PETSc mailing list)
     2. ~Don't remove points from the halos and instead migrate them process-to-process by looking at the halo ranks iteratively until all points are located or placed out-of-global-mesh.~ <- doesn't work because points in mesh might still not be in the halos
     3. If a point is not in rank-owned space (i.e. in halos or not found on local mesh at all) then come up with rank candidates for each point. Migrate point to rank candidate. Keep going until all points are in rank-owned space (i.e. not in halos) or have been removed from mesh. Libspatialindex should make this easier: 
        - All ranks should share to each other their partition's axis-aligned bounding boxes. The local libspatialindex instance can then be given the list of bounding boxes and points and be told which bounding box each point is in (somehow - I'll need to look into this carefully since I don't really understand this in any detail. Some form of voting algorithm may be needed). Points are then sent to the relevant candidate process. For high order meshes you probably need to project the coordinates field to bernstein polynomials first to avoid bounding of node locations cutting through regions of the mesh.  (ask @dham and @rckirby for help here)

**Comment by ReubenHill** [comment]
I probably ought to consider switching the warning about lost points to ON by default. If I broadcast all points to all processes as an intermediate step then the communications penalty of broadcasting all points to check for missing points is already there!

**Comment by ReubenHill** [comment]
>   2. [ ]  Avoid so much communication by migrating only necessary points **(efficient but harder)**. Ways to do this:
>      ...
>      3. If a point is not in rank-owned space (i.e. in halos or not found on local mesh at all) then come up with rank candidates for each point. Migrate point to rank candidate. Keep going until all points are in rank-owned space (i.e. not in halos) or have been removed from mesh. Libspatialindex should make this easier:
>         
>         * All ranks should share to each other their partition's axis-aligned bounding boxes. The local libspatialindex instance can then be given the list of bounding boxes and points and be told which bounding box each point is in (somehow - I'll need to look into this carefully since I don't really understand this in any detail. Some form of voting algorithm may be needed). Points are then sent to the relevant candidate process. For high order meshes you probably need to project the coordinates field to bernstein polynomials first to avoid bounding of node locations cutting through regions of the mesh.  (ask @dham and @rckirby for help here)

To elaborate on the bounding box problem: with a high order coordinates field in lagrange polynomials you can get negative values:

![bernstein](https://user-images.githubusercontent.com/7901165/134161833-709c304f-ff55-49f5-8b47-53b31bd7bf2b.png)


(reminder - I still don't understand libspatialindex so wouldn't know how to actually implement this. Any suggestions on where to read about it would be appreciated)

**Comment by wence-** [comment]
> (reminder - I still don't understand libspatialindex so wouldn't know how to actually implement this. Any suggestions on where to read about it would be appreciated)

The bounding box lookup with libspatialindex is actually a secondary optimisation. The process works like so. You have `N` ranks, they each compute (somehow, we'll come back to that later) their local bounding box. Now all processes need to exchange bounding boxes (`MPI_Allgather`). Suppose now that each process owns approximately `Nc` cells. Point location is the following process:

Partition points into "in local cells" (`found`) and "not in local cells" (`missing`). The partitioning can be done naively at a cost of `O(Nc)` per point, at a total cost of `O(|points| Nc)`.

For the `missing` points, we need to find the process they belong on. The first step is to build a set of candidate processes by intersecting the point with the bounding boxes we've gathered. The naive implementation just searches all the bounding boxes, which is `O(N)`, at a total cost of `O(|missing| N)`.

Then you exchange missing points with candidate processes, they vote on the owner, and then eventually the point ends up somewhere.

libspatialindex gives you a tree-based search for searching bounding boxes (so it takes `O(N)` and produces instead `O(log N)` [or `O(log Nc)` for the local search]). You build it by passing the corners of the bounding boxes (see `mesh.spatial_index` for an example), then you can ask for the bounding boxes that intersect a point by calling `Index_intersects_id` (see `firedrake/locate.c`).

**Comment by wence-** [comment]
Just as a note, the problem with normal lagrange elements is not that, at higher order, the basis functions go negative per se. Instead, the problem is that we want to construct a box that is guaranteed to contain any point that lies inside the cell. So we need bounds on the minimum and maximum extent of the cell in each dimension. For linears, these bounds are attained at the vertices (so we can just min/max over the coordinate axes to get the containing bounding box). For higher order Lagrange polynomials, the extrema are not contained in the convex hull of the control points (so if we min/max over the dofs on each cell, we don't have a guarantee that the entire cell lives inside that box). Conversely, the Bernstein polynomials do admit this property (namely that the polynomial is guaranteed to lie within the convex hull of the control points), so in this latter case, if we construct a bounding box by min/max over the dofs then we're guaranteed the whole cell lives inside the box.

**Comment by ReubenHill** [comment]
Thanks @wence- . So the bounding boxes correspond to rank-local cell numbering (as one gets from, say, `mesh.locate_cell`).

Some questions:
 1. How many bounding boxes are built on a given rank for a particular distributed mesh?
 2. The term "bounding boxes" is used a lot here and I think it's context dependant:
    1. In the naive case, am I to take it that each gathered bounding box (from each rank) would correspond to _all_ the cells on a that rank? And the ordering in each case would be from zero in each case? If so, there is no cross-rank canonical ordering. How could one ever work out which rank a point might belong to in that case without sending the point to every rank?
    2.  When `mesh.spatial_index` is used with `firedrake.cython.spatialindex.bounding_boxes` one gets a smaller bounding box to search. Am I correct that this is the speed up (the non-naive approach) you outline at the end?

**Comment by wence-** [comment]
> 2\. When `mesh.spatial_index` is used with `firedrake.cython.spatialindex.bounding_boxes` one gets a smaller bounding box to search. Am I correct that this is the speed up (the non-naive approach) you outline at the end?

To this question, the input that is used to construct `mesh.spatial_index` is the bounding box of each of the cells the local process can see. So suppose the local process can see 1230 cells, then the spatial index object will have 1230 bounding boxes. To locate a point I need to check, _for each cell_, "is this point inside this cell?". Searching all 1230 cells every time I need to locate a point is expensive. I can speed this up by reducing the candidate cells I actually need to check (a point won't be inside a cell if it is outside the bounding box of that cell). So the return value of `bounding_boxes` is the set of cells (out of the 1230 on my process) whose bounding box contains the point I'm looking for, and which I can therefore use in my "is this point inside this cell?" check.

The naive way of checking if a point is inside some bounding boxes is to do a linear search through all of the boxes (this is still faster than immediately checking if the point is actually inside the cell). libspatialindex implements datastructures that are faster than linear (algorithmically) by using a tree-based search.

**Comment by ReubenHill** [comment]
Thank you for your thorough replies!

> Step (1) can be done by constructing _for each process_ a bounding box of the local mesh subdomain (and sharing those bounding boxes, so that every process knows the bounding region of all processes). There will be `nproc` such bounding boxes. So to determine which processes _might_ have the point, once I have this shared data structure, I look up my point to see which processes potentially intersect with it.

Am I to take it that such a data structure does not currently exist?
If not then I guess it ought to look like...
 - Expensive version: The collection of bounding boxes of all cells from each process. Each bounding box would be numbered `[0, N_local_cells)`.
 - Cheaper version: The collection of candidate bounding boxes that one gets from the return value of `bounding_boxes` on each process. Each bounding box would be numbered `[local_minimum, local_maximum)`. I would need to work out how to produce this without sending the point to each process first.

In both cases I would need to collect them is such a way that I (1) know their source rank and (2) maintain the ability to ask the question "is this point inside this cell?". I don't yet know how to do this either.

**Comment by wence-** [comment]
I think you're confused. The first level question is "which ranks might have this point". So the bounding box you need is the total bounding box of the rank's local mesh (6 numbers in 3D). That gives you the answer "which ranks might have the point". Then you _send_ the point to those ranks, and they proceed as previously by checking if they have the point locally. One of them wins (has the point) and votes in the affirmative.

**Comment by ReubenHill** [comment]
I suppose only broadcasting the `missing` points is a win over broadcasting _all_ points all the time

**Comment by wence-** [comment]
To build the candidate processes lookup data structure needs a round of alltoall communication:

Every rank computes a bounding box for its local part of the mesh:
```
mins = numpy.amin(mesh.coordinates.dat.data_ro, axis=0)
maxes = numpy.amax(mesh.coordinates.dat.data_ro, axis=0)

minmaxes = numpy.concatenate([mins, maxes])
```

All processes gather this data:
```
nminmax, = minmaxes.shape
allminmax = numpy.empty(mesh.comm.size*nminmax, dtype=...)
mesh.comm.Allgather(minmaxes, allminmax)
## Now everyone has the bounding boxes of every process
index = spatialindex.from_regions(allminmax, ...)
```

**Comment by ReubenHill** [comment]
Thanks, I think we are now all on the same page.
