### ISSUE TITLE
Slope limiters TODO

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#835]
We are incorporating slope limiters into the core firedrake library as a submodule.  The base functionality, implementing the Kuzmin vertex-based limiter for P1DG fields arrived as #832.  This issue will track further enhancements.

- [x] Base limiter classes, P1DG limiter
- [ ] Limiting higher order fields, using Taylor basis to limit derivatives separately
- [ ] Correctly limiting at boundaries of meshes (especially extruded meshes).  I think this requires computing averages of fields over facets.  This might be a chance to implement `CellAvg` and `FacetAvg` in tsfc.
- [ ] Fewer custom kernels (use tsfc functionality for interpolation).  Needs extension to support `MIN/MAX` access descriptors for `Dat`s in PyOP2.

**Comment by miklos1** [comment]
Last check box is #801.

**Comment by miklos1** [comment]
With respect to `CellAvg` and `FacetAvg`: FFC only implements these around coefficients and arguments, which is pretty easy, just collapse (average) the tabulation matrix along the quadrature points and then use that average value at each quadrature point. Similarly to `CellVolume` and `FacetArea`, in TSFC we could average arbitrary subexpressions, but it might be just overengineering. Would there be any use for such flexibility?

**Comment by wence-** [comment]
I don't for higher-order limiters if, at the boundary of the domain I need to limit the average of the derivatives, I presume I do...

**Comment by miklos1** [comment]
I mean, averaging derivatives is still just collapsing the tabulation matrix.
