### ISSUE TITLE
Visualisation TODO

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#842]
This issue is to track things yet to be done as regards visualisation for 1d and 2d output.
# Matplotlib stuff
- [x] Basic line plots for 1D functions.  Exact up to degree 3 (using Bezier curves), linear sub-sampling at higher degree.  `geometric_dimension > topological_dimension` not handled. `plot(function)` (#837)
- [x] Figure out how to avoid connecting lines back round on periodic meshes.
- [x] Basic plotting of a sequence of functions (as part of a time-dependent simulation). `plot([f1, f2, ...])` (#837)
- [x] 2D plotting as well as 1D.  To get disconnected domains, this is done by building a polycollection.  Currently WIP in #831.
- [x] A plotting demo.  This need not be a new demo, the existing Camassa-Holm demo (1D) could be updated to use the new plotting functionality so we can view the solution in an animated fashion.
- [x] Interactivity with jupyter notebooks.  The current animation approach doesn't give nice sliders to use with IPython notebooks.  Maybe look at [JSAnimation](https://github.com/jakevdp/JSAnimation), or using [IPython widgets](https://github.com/ipython/ipywidgets) to add interactive sliders.
- [x] Documentation.  It would be good to have a new section in the manual describing the plotting functionality and how to access it.
- [ ] Plotting of domains embedded in higher spatial dimensions?
- [x] Fix firedrake-install to build a framework python in the virtualenv on macos (so that matplotlib can be used with default macos backend).
- [x] Automatically determine reasonable number of sampling points for the high order interpolation.
# Paraview stuff

Consider using [catalyst](http://www.paraview.org/in-situ/) for in-situ visualisation, rather than requiring everyone to dump masses of PVDs. @dham may have more information about how this works.
