### ISSUE TITLE
Slate: next steps

### ISSUE THREAD

**Issue by thomasgibson** [firedrakeproject/firedrake#975]
This issue is for tracking progress on the Slate package:

- [x] Base language in working condition, with some features ready to go (localized kernels for dense linear algebra)

**TODO:**

Organization (pointed out by Lawrence):
- [x] Make `TensorBase` an abstract base class and properly document required subclass methods/properties by annotating with `@abstractmethod`/`@abstractproperty`.
- [x] Address some inconsistencies with attributes: `.tensor` vs `.tensors`

Use Slate in a python preconditioner (inspired by Rob Kirby):
- [x] The framework is there for constructing a preconditioner for RT/BDM mixed systems via hybridization. It's now a matter of designing a `PCBase` (from the matrix free package) preconditioner that does the following:
  - Takes a mixed-system and breaks the velocity space;
  - Introduces the Lagrange multipliers defined on the trace space;
  - Constructs the Slate expression executing element-wise elimination of unknowns to arrive at a system for the multipliers only;
  - Solves the global reduced system for the multipliers;
  - Performs the element-wise reconstruction of the original unknowns in Slate using the multipliers.
    - To make this step more efficient, we need to extend PyOP2 to write into mixed dats.

I believe is a significant step towards addressing #108

Other additions:
- [x] Support extruded cells.
  - Note that we will need to revise how Slate checks mesh layer info once variable column height is implemented in PyOP2
- [x] Introduce a `solve` node in Slate that uses matrix factorizations (provided by Eigen) to solve elemental systems rather than directly inverting the local dense matrices.
- [x] Introduce kernel caching.
- [x] Compose Slate with the matrix-free interface.
- [x] Multiple domains/subdomains 
- [ ] Strong boundary condition support at the Slate level.
- [x] Support tensor blocking.
   - [ ] Entiry indexing: row-sum (or diagonal) mass-lumping.
- [ ] Operator that extracts the diagonal of a matrix.
- [ ] Should `TensorBase` inherit from `gem.node.Node`?

If y'all have other suggestions, feel free to post and/or edit these notes.
